### ISSUE TITLE
coalesce and arrays

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#1076]
### ldproxy Version

3.5.0

### Current Behavior

`coalesce` does not work in an array. The following feature property "foo" always returns an array with "bar" only set in the first array item. When the first "foo.bar" value is processed, the path "foo.bar" is added to `MappingOperationsTransformer.coalesces`. As a result, all subsequent "foo.bar" values are skipped in `MappingOperationsTransformer.valueCoalesce()`.

```yaml
foo:
  type: OBJECT_ARRAY
  sourcePath: "[id=id]foo_table"
  properties:
    baz:
      type: STRING
    bar:
      type: VALUE
      coalesce:
      - sourcePath: bar_stringValue
        type: STRING
      - sourcePath: bar_integerValue
        type: INTEGER
      - sourcePath: bar_booleanValue
        type: BOOLEAN
```

### Expected Behavior

All values are returned, not only the first one.

### Steps to Reproduce

See above.
