### ISSUE TITLE
configurable minimum maturity and maintenance levels

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#1149]
Add an option in `cfg.yml` to ignore modules that don't match the minimum levels. The default would be:

```yml
modules:
  minMaturity: CANDIDATE
  minMaintenance: LOW
```
