### ISSUE TITLE
Issue with SQL query generation, incorrect mapping of filters

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#1193]
Given the following provider schema:

```yaml
  abschnitt:
    sourcePath: /abschnitt
    properties:
      oid:
        sourcePath: oid
        type: STRING
        role: ID
      strasse:
        sourcePath: '[oid=id]zwischentab{filter=role=''zu_Strasse''}/[rid=oid]strasse'
        type: OBJECT
        properties:
          strassenbezeichnung:
            sourcePath: '[oid=id]zwischentab{filter=role=''hat_Strassenbezeichnung''}/[rid=oid]strassenbezeichnung'
            type: OBJECT
            properties:
              strassenklasse:
                sourcePath: '[strassenklasse=oid]strassenklasse'
                type: OBJECT
                properties:
                  kennung:
                    sourcePath: kennung
                    type: STRING
              strassennummer:
                sourcePath: strassennummer
                type: INTEGER
              zusatzbuchstabe:
                sourcePath: zusatzbuchstabe
                type: STRING
```

Then the following SQL queries are generated for these properties:

```sql
SELECT A.oid AS SKEY, E.oid AS SKEY_1, E.strassennummer, E.zusatzbuchstabe 
FROM abschnitt A 
JOIN zwischentab B ON (A.oid=B.id AND (D.role = 'hat_Strassenbezeichnung')) 
JOIN strasse C ON (B.rid=C.oid) 
JOIN zwischentab D ON (C.oid=D.id AND (D.role = 'hat_Strassenbezeichnung')) 
JOIN strassenbezeichnung E ON (D.rid=E.oid) 
WHERE (A.oid >= '11200' AND A.oid <= '11218') 
ORDER BY 1,2;

SELECT A.oid AS SKEY, E.oid AS SKEY_1, F.oid AS SKEY_2, F.kennung 
FROM abschnitt A 
JOIN zwischentab B ON (A.oid=B.id) 
JOIN strasse C ON (B.rid=C.oid) 
JOIN zwischentab D ON (C.oid=D.id) 
JOIN strassenbezeichnung E ON (D.rid=E.oid) 
JOIN strassenklasse F ON (E.strassenklasse=F.oid) 
WHERE (A.oid >= '11200' AND A.oid <= '11218') 
ORDER BY 1,2,3;
``` 

In the first query, `D.role = 'hat_Strassenbezeichnung'` should be `B.role = 'zu_Strasse'`. The current query results in an error.

In the second query, the filter predicates are not included in the query.
