### ISSUE TITLE
Title and Description not taking effect for geometry properties

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#1195]
### Discussed in https://github.com/interactive-instruments/ldproxy/discussions/1194

<div type='discussions-op-text'>

<sup>Originally posted by **ghelle-fhh** April  4, 2024</sup>
Hello,

We have begun to work more with the title, description and unit configurations and came across a small issue. When we configure a description and a title for a property with the role "primary_geometry" as such:

```
geographicextent:
   sourcePath: geographicextent
   type: GEOMETRY
   label: Geographic Extent
   description: Test
   role: PRIMARY_GEOMETRY
   geometryType: POLYGON
```

The configured description does not appear in the collection schema:

```
    "geographicextent" : {
      "x-ogc-role" : "primary-geometry",
      "format" : "geometry-polygon"
    },
```

We would expect the output to be:

```
    "geographicextent" : {
      "title" : "Geographic Extent",
      "description" : "Test",
      "x-ogc-role" : "primary-geometry",
      "format" : "geometry-polygon"
    },
```

For the role "ID" and other properties we are able to configure the descritption, title and also unit, it's only the role "primary_geometry" where we observe this behavior. 

Many thanks!</div>
