### ISSUE TITLE
basic joint catalog

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#1285]
This allows to provide a joint API catalog for multiple ldproxy instances. It is a very basic implementation that requires manual configuration every time when an API is added or removed. 
On the main instance the additional entries have to be configured in the `FOUNDATION` defaults and on all instances the home URL has to be set to the main instance in the `HTML` defaults. Example:

```yml
- buildingBlock: FOUNDATION
  apiCatalogLabel: Joint API Catalog
  apiCatalogDescription: The following APIs are available.
  apiCatalogAdditionalEntries:
  - id: demo-vineyards
    title: Vineyards in Rhineland-Palatinate, Germany
    description: Have you ever wondered where the wine ...
    landingPageUri: https://demo.ldproxy.net/vineyards
- buildingBlock: HTML
  homeUrl: https://demo.ldproxy.net
```
