### ISSUE TITLE
ogc api features: general performance issue

### ISSUE THREAD

**Issue by AntonHardock** [interactive-instruments/ldproxy#1345]
### Describe the Feature Request

Dear developers,

the LGV Hamburg deploys ldproxy in production mainly to provide [OGC API - Features](https://api.hamburg.de/datasets/v1).
We started to phase out the use of Web Feature Services in our Geoportals.
In doing so, we ran into a general performance-issue that most probably are related to ldproxy.

### Describe the Use Case

One use-case is to embed our tree register dataset in a dedicated geoportal, including a tool
to filter specific tree types, among others. Here is a test-instance: https://test.geoportal-hamburg.de/strassenbaumkataster/
Layer “Straßenbaumkataster (WFS)” requests our older WFS Endpoint (provided by [deegree.Pro](https://deegree.pro/)).
Layer “Straßenbaumkataster Hamburg” requests the equivalent OAF Endpoint.
Both use the same database with identical datasource configurations (table, columns and datatypes).
Now, when activating the OAF Layer and navigating through Hamburg (zoom level 1:10.000), the OAF endpoint responds significantly slower than the WFS counterpart.

#### Example OAF Request

Here is one example OAF-request from that use case, as sent by the application:

```
GET /datasets/v1/strassenbaumkataster/collections/strassenbaumkataster/items?limit=10000&bbox=568092.090213174%2C5937873.798096794%2C570364.8598192118%2C5939736.46375762&bbox-crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F25832&crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F25832 HTTP/1.1
Accept: application/geo+json
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection: keep-alive
DNT: 1
Host: api.hamburg.de
Origin: https://test.geoportal-hamburg.de/
Referer: https://test.geoportal-hamburg.de/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0
sec-ch-ua: "Not A(Brand";v="8", "Chromium";v="132", "Microsoft Edge";v="132"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
```

Here is the corresponding Windows curl snippet I used:

```
curl -o nul ^"https://api.hamburg.de/datasets/v1/strassenbaumkataster/collections/strassenbaumkataster/items?limit=10000^&bbox=568092.090213174^%^2C5937873.798096794^%^2C570364.8598192118^%^2C5939736.46375762^&bbox-crs=http^%^3A^%^2F^%^2Fwww.opengis.net^%^2Fdef^%^2Fcrs^%^2FEPSG^%^2F0^%^2F25832^&crs=http^%^3A^%^2F^%^2Fwww.opengis.net^%^2Fdef^%^2Fcrs^%^2FEPSG^%^2F0^%^2F25832^"  -w '%{size_download}'^
  -H ^"Accept: application/geo+json^" ^
  -H ^"Accept-Language: de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6^" ^
  -H ^"Connection: keep-alive^" ^
  -H ^"DNT: 1^" ^
  -H ^"Origin: https://test.geoportal-hamburg.de^" ^
  -H ^"Referer: https://test.geoportal-hamburg.de/^" ^
  -H ^"Sec-Fetch-Dest: empty^" ^
  -H ^"Sec-Fetch-Mode: cors^" ^
  -H ^"Sec-Fetch-Site: cross-site^" ^
  -H ^"User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0^" ^
  -H ^"sec-ch-ua: ^\^"Not A(Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"132^\^", ^\^"Microsoft Edge^\^";v=^\^"132^\^"^" ^
  -H ^"sec-ch-ua-mobile: ?0^" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^"
```

#### Analog WFS Request

This is the counterpart WFS-request:

```
GET /HH_WFS_Strassenbaumkataster?service=WFS&version=1.1.0&request=GetFeature&srsName=EPSG%3A25832&typeName=strassenbaumkataster&bbox=568092.090213174,5937873.798096794,570364.8598192118,5939736.46375762,EPSG:25832 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection: keep-alive
DNT: 1
Host: geodienste.hamburg.de
Origin: https://test.geoportal-hamburg.de/
Referer: https://test.geoportal-hamburg.de/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0
sec-ch-ua: "Not A(Brand";v="8", "Chromium";v="132", "Microsoft Edge";v="132"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
```

Again, the curl snippet for reproduction:

```
Curl -o nul ^"https://geodienste.hamburg.de/HH_WFS_Strassenbaumkataster?service=WFS^&version=1.1.0^&request=GetFeature^&srsName=EPSG^%^3A25832^&typeName=strassenbaumkataster^&bbox=568092.090213174,5937873.798096794,570364.8598192118,5939736.46375762,EPSG:25832^"  -w '%{size_download}'^
  -H ^"Accept: */*^" ^
  -H ^"Accept-Language: de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6^" ^
  -H ^"Connection: keep-alive^" ^
  -H ^"DNT: 1^" ^
  -H ^"Origin: https://test.geoportal-hamburg.de^" ^
  -H ^"Referer: https://test.geoportal-hamburg.de/^" ^
  -H ^"Sec-Fetch-Dest: empty^" ^
  -H ^"Sec-Fetch-Mode: cors^" ^
  -H ^"Sec-Fetch-Site: cross-site^" ^
  -H ^"User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0^" ^
  -H ^"sec-ch-ua: ^\^"Not A(Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"132^\^", ^\^"Microsoft Edge^\^";v=^\^"132^\^"^" ^
  -H ^"sec-ch-ua-mobile: ?0^" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^"

```

#### sample response times, OAF vs WFS
 
<img src="https://github.com/user-attachments/assets/028ea61e-27ee-43ac-9853-32b870f5825f" width=55% height=55%>

<img src="https://github.com/user-attachments/assets/cefff9f6-de0a-4f3b-ab67-90973ee15b9e" width=55% height=55%>

The difference in download time is roughly 10x. The server response time also differs significantly.
We were able to reproduce this performance gap in a more controlled environment,
comparing both deployments locally in docker (images used: deegree/deegree3-docker and iide/ldproxy)
The version of ldproxy used in production is: 3.6.4
When comparing in docker, we also tested the newest version: 4.2.0
Performance was comparable in both versions.

We also tested the impact of the `required:true` setting for the geometry (see provider snippet below)
We expected a reduction of the download time, which did not seem to be the case.

### Describe Preferred Solution

In general, we need requests as provided in the example to take milliseconds, not seconds.
Could you investigate this issue further? Is there some configuration that we might have overlooked?

### Additional Information

Here is a snippet of our provider configuration:

```
id: strassenbaumkataster
entityStorageVersion: 2
providerType: FEATURE
featureProviderType: SQL
nativeCrs:
  code: 25832
  forceAxisOrder: NONE
connectionInfo:
  connectorType: SLICK
  dialect: PGIS
  database: fachdaten
  host: ${HOST}
  user: ${USER}
  password: ${PASSWORD}
types:
  strassenbaumkataster:
    sourcePath: /${SCHEMA}.${TABLE}{sortKey=gid}{primaryKey=gid}
    type: OBJECT
    properties:
      gid:
        sourcePath: gid
        label: gid
        description: null
        unit: ""
        type: INTEGER
        role: ID
      […]
      geom:
        sourcePath: geom
        type: GEOMETRY
        label: geom
        description: null
        unit: ""
        role: PRIMARY_GEOMETRY
        geometryType: MULTI_POINT
        constraints:
            required: true
```
