### ISSUE TITLE
add provider schema information

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#162]
Support configuration of additional information for the schema defined by the provider. That is necessary for example to generate JSON Schema or OpenAPI definitions and for HTML encodings.

The following fields will be added (for use cases and descriptions, see the example):

#### Provider

* defaultLanguage
* codelists

#### Type

* label
* description
* properties

#### Property

* label
* description
* properties
* constraints
* objectType
* valueType
* geometryType
* transformers

#### Example

This example should cover every use case for the new fields.

```yaml
defaultLanguage: de # optional, defines language used in labels and descriptions, absent means undefined

types:
  observationsubject:
    path: /observationsubject
    label: Untersuchungsobjekt
    description: Ein Untersuchungsobjekt ist entweder eine Probe für Untersuchungen
      im Labor oder eine In-Situ-Messung
    properties:
      id:
        path: id
        type: STRING
        role: ID
        label: Objekt-Id
        description: Eindeutige Id des Objekts
        constraints:
          regex: [a-zA-Z0-9_]{3,} # regex, min length 3, only allowed characters
      type:
        path: _type
        type: STRING
        label: Art
        constraints:
          codelist: geoval_type # enum from codelist keys
          enum:
            - Borehole # alternatively, explicit enum
            - ...
      shortName:
        path: shortname
        type: STRING
        transformers:
          codelist: nullValues # references local codelist to transform certain values to null 
      geomLowerPoint:
        path: geomlowerpoint
        type: GEOMETRY
        geometryType: POINT
      explorationSite:
        path: [explorationsite_fk=id]explorationsite
        type: OBJECT
        objectType: Link # free value, can be used for case detection in transformer and as identifier in json schema
        label: Aufschlußpunkt
        properties:
          title:
            path: shortname
            type: STRING
          href:
            path: id
            type: STRING
            constraints:
              required: true
      process:
        path: [id=observationsubject_fk]observationsubject_process/[process_fk=id]process
        type: OBJECT_ARRAY
        objectType: Link
        label: Versuche
        constraints: # array constraints
          minOccurrence: 1
          maxOccurrence: 3
        properties:
          title:
            path: category_fk
            type: STRING
          href:
            path: id
            type: STRING
            constraints:
              required: true 
      filterValues:
        path: [id=observationsubject_fk]observationsubject_filtervalues
        type: OBJECT_ARRAY
        objectType: FilterValue
        label: Leitkennwerte
        properties:
          property:
            path: filtervalueproperty_fk
            type: STRING
            label: Eigenschaft
          measure:
            path: resultmeasure
            type: FLOAT
            label: Messwert
            constraints: # constraints on numbers
              min: 0.0
              max: 100.0
          classification:
            path: [id=filtervalue_fk]filtervalue_resultclassification/classificationcode_fk
            type: VALUE_ARRAY
            valueType: STRING  
            label: Klassifikationen

codelists: # local codelist definitions, have preference over global codelists
  nullValues:
    No Information: null
    '-1': null
```

#### Future work

- i18n
```
types:
  observationsubject:
    i18n:
      en:
        label: Observation subject
        description: ...
    properties:
      id:
        i18n:
          en: 
            label: Object id
```
- constraint validation
```
constraintValidation: NONE # don't check if values fulfil constraints
```
```
constraintValidation: LAX # log a warning if a value does not fulfil the constraints, but proceed as normal
```
```
constraintValidation: STRICT # if value is not required, log warning and skip value, otherwise throw error
```
