### ISSUE TITLE
support auto-reload of entity configurations

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#267]
Support a `watch` option for the store, that will trigger a rolling update of the affected entities when a file changes. See also #266.

**Comment by azahnen** [comment]
The option was implemented:

```yml
store:
  mode: READ_ONLY
  watch: true
```

When the store is not in `READ_ONLY` mode, the `watch` option is ignored.
