### ISSUE TITLE
add options for tile cache seeding

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#278]
Currently tile cache seeding is triggered when a service starts. It will then generate all non-existing tiles. Recreating tiles requires a manual deletion of files.

The seeding will only generate one tile for one service at a time so that most of the resources can still be used for processing 
 client requests. 

This improvement would add options to run seeding periodically instead of or in addition to the service startup, to purge the cache before the seeding starts and to fully use available resources to generate the cache as fast as possible.

```yml
seedingOptions:
  runOnStartup: false # disable seeding on service startup
  runPeriodic: 0 0 * * * # schedule a cron job to trigger seeding every day at midnight
  purge: true # purge the cache before seeding starts
  parallel: true # generate as many tiles in parallel as the provider can handle
```

**Comment by cportele** [comment]
Looks good. As discussed, it would be good, if `parallel` could be a number of max threads for generating tiles in parallel (`-1` could be the current `true`).

A related topic: `TilesQueriesHandlerImpl.getMultiLayerTileResponse` currently processes each layer/collection sequentially, both during seeding and in responses to tile requests. For multi-layer tiles with many layers parallel processing would accelerate this, if the server can cope with the load. 

This is only really important for tile requests (for seeding the sequential approach should be fine as we would control parallel tile generation using the `parallel` parameter), but since the same code is used for both kinds of multi-layer tile generation, can we take this into account in this discussion, too? Maybe by another tiles configuration parameter to control how many layers can be processed in parallel for tile requests (default is 1)? For seeding we would always use 1.

**Comment by azahnen** [comment]
For the simple options, the configuration looks like this:

```yml
- buildingBlock: TILES
  tileProvider:
    type: FEATURES
    seedingOptions:
      runOnStartup: false
      runPeriodic: '* * * * *' # schedule a cron job to trigger seeding every minute
      purge: true
```

When the seeding is still in progress when a scheduled seeding tries to start, the scheduled seeding will be ignored. So there is no harm in scheduling it every minute for testing.

For the multi-threaded seeding, an option in the `cfg.yml` has to be set first:

```
backgroundTasks:
  maxThreads: 4 # the default is 1, which behaves as before
```

This allows multiple background tasks in the first place. So even without any changes to the seeding options, this would allow the seeding for 4 services to run in parallel.

When maxThreads in the seeding options is greater than 1, that means divide the seeding into n parts, where n is the number of available threads when the seeding is about to start, capped by `seedingOptions.maxThreads`.

```yml
- buildingBlock: TILES
  tileProvider:
    type: FEATURES
    seedingOptions:
      maxThreads: 2
```

So for example setting `seedingOptions.maxThreads` to 2 with the given `cfg.yml` will divide the seeding into 2 parts if at least 2 of the 4 threads are available. If 3 threads are used by other services, it will not be divided. And if all 4 threads are busy, it waits until at least 1 becomes available (like without any of the new options).
