### ISSUE TITLE
Various minor issues identified during testing

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#539]
* [x] If a transformation is specified for an OBJECT-valued property (e.g. a remove transformation in FEATURES_HTML) and validation is executed during startup, the following error is reported: "A transformation for property 'someObject' in collection 'foo' is invalid, because the property was not found in the provider schema."
* [x] When a new API is created in the Manager, values for `sourcePaths` and `forcePolygonCCW` with the default values are created for every single schema (object, property).
* [x] If `max` is set in constraints in the provider configuration, the value is converted to a `min` constraint in JSON. Schema.
* [x] If properties are marked as required (through a `required` constraint or `role: ID`), the JSON Schema includes entries like `"required" : [ "_ID_ROLE_gml_id" ]`, but there is no property of that name. 
* [x] The property schema below does not work as expected (gitea repository: ws2111). The resulting HTML and GeoJSON is included below, too. It looks as if "myProperty" is not sent to the encoder, only its contents. Using a single `sourcePath` or declaring `rel` and `tab1` as properties does not change the behaviour. Am I missing something or is this a bug?

```yaml
      myProperty:
        sourcePath: '[id=fk1]rel{filter=rel=''myProperty'' AND tab1=''myTab''}'
        type: OBJECT_ARRAY
        objectType: Link
        properties:
          title:
            sourcePaths:
            - fk2
            - tab2
            type: STRING
            transformations:
              stringFormat: '{{tab2}}/{{fk2}}'
          href:
            sourcePaths:
            - fk2
            - tab2
            type: STRING
            transformations:
              stringFormat: '{{serviceUrl}}/collections/{{tab2}}/items/{{fk2}}'
```

```json
"properties":{
    "gml_id":"XPLAN_BP_BEREICH_ae999c56-6ef0-4ad7-aebe-53aba7b0baff",
    "nummer":0,
    "versionbaunvodatum":"1990-01-23+01:00",
    "title":"bp_wegerecht/1",
    "href":"http://localhost:7080/rest/services/bplan/collections/bp_wegerecht/items/1"
}
```

<img width="581" alt="Bildschirmfoto 2021-11-25 um 11 20 15" src="https://user-images.githubusercontent.com/4245251/143425996-9cd6b685-1c54-4afa-9cd7-df5ad89fcb9b.png">
