### ISSUE TITLE
trivial markdown is not translated correctly into HTML (stringFormat transformation in FEATURES_HTML)

### ISSUE THREAD

**Issue by rkoblenzer** [interactive-instruments/ldproxy#544]
In service configuration, complex stringFormat transformations with markdown, e.g. with tables, work as expected, but simple markdown strings (e.g. with `\n` only) are not translated correctly into HTML.

```yml
- buildingBlock: FEATURES_HTML
  transformations:
    bez:
      stringFormat: "{{value | replace:';':'\n' | markdown}}"
```
Result: I get `&#10;` in the position where I would expect `<br/>`.

(Configuration example: lika)

Note: Low priority. Current release (3.0) and the pre-release (master) are both affected.
