### ISSUE TITLE
document postgresql feature changes

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#632]
When #626 is merged, add docs to `FeatureChangesPgListener`.

**Provider**
```yml
extensions:
    - type: FEATURE_CHANGES_PG
      enabled: true
      listenForTypes: # optional, default is to listen for all types
        - notam
```

**PostgreSQL**
```sql
CREATE OR REPLACE FUNCTION public.notam_trigger()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
   DECLARE
      bbox box2d;
   BEGIN
        IF (TG_OP = 'DELETE') THEN
            bbox = box2d(ST_Transform(OLD.geom,4326));
            PERFORM pg_notify(notam_notam, concat_ws(',', TG_OP, TG_TABLE_NAME, OLD._id, COALESCE(to_char(OLD.valid_time_begin, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),'NULL'), COALESCE(to_char(OLD.valid_time_end, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),'NULL'), st_xmin(bbox), st_ymin(bbox), st_xmax(bbox), st_ymax(bbox)));
            RETURN OLD;
        ELSIF (TG_OP = 'INSERT') THEN
            bbox = box2d(ST_Transform(NEW.geom,4326));
            PERFORM pg_notify(notam_notam, concat_ws(',', TG_OP, TG_TABLE_NAME, NEW._id, COALESCE(to_char(NEW.valid_time_begin, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),'NULL'), COALESCE(to_char(NEW.valid_time_end, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),'NULL'), st_xmin(bbox), st_ymin(bbox), st_xmax(bbox), st_ymax(bbox)));
            RETURN NEW;
        END IF;
    END;
$function$
;

CREATE TRIGGER notam_update
AFTER INSERT OR UPDATE OR DELETE ON notam
    FOR EACH ROW EXECUTE PROCEDURE notam_trigger();
```

See #630  and #487.
