### ISSUE TITLE
tile provider cache levels are ignored on deserialization

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#850]
### ldproxy Version

v3.3.0

### Current Behavior

When using the new tile provider entities, `levels` for `caches` is ignored in deserialization. The result is that no tiles will be seeded unless `layerLevels` is defined.

### Expected Behavior

The `levels` are considered when seeding.

### Steps to Reproduce

Define a tile provider like this in `store/entities/providers` and look at the seeding results.

```
---
id: vineyards-tiles
providerType: TILE
providerSubType: FEATURES
caches:
- type: IMMUTABLE
  storage: PLAIN
  levels:
    WebMercatorQuad:
      min: 5
      max: 11
layers:
  vineyards:
    id: vineyards
```
