### ISSUE TITLE
Support JSON-values in SQL databases

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#907]
Add support for JSON values in the columns of a table used in an SQL feature provider. This capability supports simpler database schemas and reduce joins.

In PostgreSQL the column could be of type `jsonb`, `json` or a string column. `jsonb` will usually be the best option, if the order of the members is not important for objects.

In SQLite the type would be `TEXT`. SQLite has features to support such columns.

The content would be defined in the feature schema as usual, i.e. the schema of the JSON content would be specified explicitly. 

An extension in the `sourcePath` to identify a column as JSON is probably necessary.

A simple example:

**SQL table**

| id | name | link | numbers |
| --- | --- | --- | --- |
| 1 | one | {"label": "foo", "url": "https://foo.bar"} | [ 1, 2, 3 ]

**Mapping**

```yaml
types:
  example:
    sourcePath: /example
    type: OBJECT
    properties:
      id:
        sourcePath: id
        type: INTEGER
        role: ID
      name:
        sourcePath: name
        type: STRING
      link:
        sourcePath: '[JSON]link'
        type: OBJECT
        objectType: Link
        properties:
          title:
            sourcePath: label
            type: STRING
          href:
            sourcePath: url
            type: STRING
      numbers:
        sourcePath: '[JSON]numbers'
        type: VALUE_ARRAY
        valueType: INTEGER
``` 

**GeoJSON instance**

```json
{
  "type": "Feature",
  "id": 1,
  "geometry": null,
  "properties": {
    "name": "one",
    "link": {
      "title": "foo",
      "href": "https://foo.bar"
    },
    "numbers": [1, 2, 3],
  }
}
```

Support for such properties or their sub-properties as queryables or sortables could be added in the future, but would not be required initially.
