### ISSUE TITLE
JSON Schema as feature schema

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#908]
An ldproxy feature schema is defined in YAML/JSON ([documentation](https://docs.ldproxy.net/providers/feature/#types)).

For cases where an external JSON Schema exists that is consistent with the schema in the feature provider, this JSON Schema could be used to generate the feature schema from the JSON Schema during start-up.

A new keyword `schema` would be defined to reference the JSON Schema document.

`schema` could be used for the complete schema of a feature type or for any sub-property.

Examples:

```yaml
types:
  foo:
    sourcePath: /foo
    schema: foo.json
  bar:
    sourcePath: /bar
    type: OBJECT
    properties:
      id:
        sourcePath: id
        type: INTEGER
        role: ID
      name:
        sourcePath: name
        type: STRING
      link:
        sourcePath: '[JSON]link'
        schema: link.json
```

Only a subset of JSON Schema would be supported, i.e., the JSON Schema must be directly mappable to an ldproxy feature schema.
