### ISSUE TITLE
support allOf in provider schema

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#931]
This will introduce the `allOf` composition from JSON schema to the provider schema. There are two known use cases:

**Define only some properties using an external JSON schema (#908)** 

```yaml
types:
  example:
    sourcePath: /main
    type: OBJECT
    allOf:
    - properties:
        id:
          sourcePath: id
          type: INTEGER
          role: ID
    - schema: names.json
```

This comes in really handy when used along with JSON columns (#907):

```yaml
types:
  example:
    sourcePath: /main
    type: OBJECT
    allOf:
    - properties:
        id:
          sourcePath: id
          type: INTEGER
          role: ID
    - sourcePath: '[JSON]names'
      schema: names.json
```

**Using columns from a joined table in the main feature**

This was already supported but pretty cumbersome since the join had to be repeated for every property.

*Before*

```yaml
types:
  example:
    sourcePath: /main
    type: OBJECT
    properties:
      id:
        sourcePath: id
        type: INTEGER
        role: ID
      name1:
        sourcePath: '[id=id]names/name1'
        type: STRING
      name2:
        sourcePath: '[id=id]names/name2'
        type: STRING
```

*After*

```yaml
types:
  example:
    sourcePath: /main
    type: OBJECT
    allOf:
    - properties:
        id:
          sourcePath: id
          type: INTEGER
          role: ID
    - sourcePath: '[id=id]names'
      properties:
        name1:
          sourcePath: name1
          type: STRING
        name2:
          sourcePath: name2
          type: STRING
```
