### ISSUE TITLE
Feature Schema: Data type for references to features

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#970]
### Describe the Feature Request

So far, references to other features are typically encoded as a `Link` object with `href` and `title` properties. In some cases, it would better to have use the "foreign key" (the `featureId` of the referenced feature) instead.

For referenced features in the same API we also need the `collectionId`. For features in another API implementing OGC API Features we also need the URI of the `apiLandingPage`.

NOTE: The `Link` object approach can still be used. Existing configurations will continue to work without changes.

### Describe the Use Case

An example where the "foreign key" would be better:

A client has a feature collection where the features reference features in another collection. The clients wants to fetch the related features to process their information.

In the case of links, the client has to sent one request per link (or try to parse the link URIs for the feature ids).

In the case of foreign keys, the client can send a single request to retrieve the features, e.g. using a CQL2 filter like `id IN (1, 3, 7, 16, 53, 59, 64, 99)` where `id` is a queryable representing the feature id.

### Describe Preferred Solution

Add new types `FEATURE_REF` and `FEATURE_REF_ARRAY` to the feature schema. The value type of the property can be `STRING` or `INTEGER`, depending on type of the feature property with the role `ID`. `STRING` is the default.

To indicate the target feature type, a new annotation `refType` can be used. Note that since the schema does not know anything about OGC API or Collections, this is the id of the feature type in the schema, not the id of the collection in the API. When an API link is derived for the reference, the feature type id may need to be mapped to the collection id.

```yaml
      abs:
        label: Abschnitt/Ast
        description: 16-stellige Kennung des Abschnittes oder Astes
        type: FEATURE_REF
        refType: abschnitteaeste
        sourcePath: abs
```

For features that are not published in the same API, instead of `refType` we could provide a URI template in a new annotation `refUriTemplate` with `{value}` for the foreign key so that a link can be constructed when needed. Both single and double curly braces should be supported.

```yaml
      abs:
        label: Abschnitt/Ast
        description: 16-stellige Kennung des Abschnittes oder Astes
        type: FEATURE_REF 
        refUriTemplate: 'https://demo.ldproxy.net/strassen/collections/abschnitteaeste/items/{value}'
        sourcePath: abs
```

In addition, the schema of the features in a collection should be adapted as discussed in a [proposal in the OGC Features API working group](https://github.com/opengeospatial/ogcapi-features/issues/740#issuecomment-1501758135).
