### ISSUE TITLE
Feature Schema: Support representations that better match the application schema

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#971]
### Describe the Feature Request

If feature data in an SQL feature provider is based on an application schema that uses inheritance, the current capabilities often cannot properly represent the data in the concepts of the application schema. As a result, the data cannot conform to, for example, a JSON Schema or an XML Schema generated based on an encoding rule.

### Describe the Use Case

Two examples:

1. An application schema has a feature type `Foo` with an attribute `bar` that can be a string, integer or boolean value. In the DB and the feature schema, this could look like this:

```yaml
foo:
  type: OBJECT
  properties:
    bar_stringValue:
      type: STRING
      sourcePath: bar_stringValue
    bar_integerValue:
      type: INTEGER
      sourcePath: bar_integerValue
    bar_booleanValue:
      type: BOOLEAN
      sourcePath: bar_booleanValue
```

However, in a JSON Schema, `bar` will likely be specified as `"bar" : { "type" : [ "string", "integer", "boolean" ] }` and this is not a representation that ldproxy can currently create.

2. An application schema has a feature type `Foo` with an association role `bar` to an abstract class `Baz`, which has multiple subclasses (`Baz1`, ..., `Bazn`). In the DB and the feature schema, this could look like this (using #970):

```yaml
foo:
  type: OBJECT
  properties:
    id:
      type: STRING
      sourcePath: id
      role: ID
    bar_baz1:
      type: FEATURE_REF_ARRAY
      sourcePath: '[id=foo_fk]baz1/id'
    bar_baz2:
      type: FEATURE_REF_ARRAY
      sourcePath: '[id=foo_fk]baz2/id'
    bar_bazn:
      type: FEATURE_REF_ARRAY
      sourcePath: '[id=foo_fk]bazn/id'
```

In a JSON Schema of the application schema, `bar` will likely be specified as a single member/property with an array of all values from the `bar_bazx` arrays. Again, this is not a representation that ldproxy can currently create.

## Overview

Supporting the requirement has two aspects: Add support in the Feature Schema itself for such schemas and add support in the processing of the data. In both use cases, have a more general 'outer' schema of the `bar` property and more specific 'inner properties' with their own specialized schema that are processed to determine the value of `bar` using some operation.

## Type compatibility

Constraints on the types of 'inner properties' depending on the type of the 'outer' property are shown in the table below. A new type `VALUE` is introduced, a generalization of `INTEGER`, `FLOAT`, `STRING`, `BOOLEAN`, `DATETIME`, and `DATE`.

| Outer type  | Valid inner types  | Remarks |
|---|---|---|
| `VALUE`  |  `INTEGER`, `FLOAT`, `STRING`, `BOOLEAN`, `DATETIME`, `DATE`  |   |
| `INTEGER`  |  `INTEGER` |   |
| `FLOAT`  |  `FLOAT` |   |
| `STRING`  |  `STRING`  |   |
| `BOOLEAN`  |  `BOOLEAN`  |   |
| `DATETIME`  |  `DATETIME`  |   |
| `DATE`  |  `DATE`  |   |
| `OBEJCT`  |  `OBJECT`  | Different `objectType` with different schemas can be used  |
| `GEOMETRY`  |  `GEOMETRY`  | Different `geometryType` can be used  |
| `FEATURE_REF `  |  `FEATURE_REF `  | Different `refType` can be used  |
| `VALUE_ARRAY`  |  `VALUE_ARRAY`, `INTEGER`, `FLOAT`, `STRING`, `BOOLEAN`, `DATETIME`, `DATE`  |   |
| `OBJECT_ARRAY`  |  `OBJECT_ARRAY`, `OBJECT`  | Different `objectType` with different schemas can be used  |
| `FEATURE_REF_ARRAY `  |  `FEATURE_REF_ARRAY`, `FEATURE_REF `  | Different `refType` can be used  |

## Operations

Initially, we should support two operations: `coalesce` (first use case) and `concat` (second use case).

### `coalesce`

`coleasce` uses the first value that is not `null`.  `coleasce` would not be supported on arrays.

We can then write the feature schema of the first use case as: 

```yaml
foo:
  type: OBJECT
  properties:
    bar:
      type: VALUE
      coalesce:
      - sourcePath: bar_stringValue
        type: STRING
      - sourcePath: bar_integerValue
        type: INTEGER
      - sourcePath: bar_booleanValue
        type: BOOLEAN
```

### `concat`

`concat` concatenates all values - not the arrays are concatenated, if the type of an inner property is an array, but the items in the array(s). `concat` can only be used on array properties.

We can then write the feature schema of the second use case as: 

```yaml
foo:
  type: OBJECT
  properties:
    id:
      type: STRING
      sourcePath: id
      role: ID
    bar:
      type: FEATURE_REF_ARRAY
      concat:
      - sourcePath: '[id=foo_fk]baz1/id'
        refType: baz1
      - sourcePath: '[id=foo_fk]baz2/id'
        refType: baz2
      - sourcePath: '[id=foo_fk]bazn/id'
        refType: bazn
```
